[build]
  command = "chmod +x netlify-build.js && ./netlify-build.js"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  YARN_FLAGS = "--frozen-lockfile" 