[build]
  command = "yarn netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  YARN_FLAGS = "--ignore-engines"
  NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs" 