[build]
  command = "chmod +x netlify-build.js && ./netlify-build.js"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1" 